INSERT INTO courses VALUES (null, 'BSIT', 'BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY', 1, 1,NULL,NULL);
INSERT INTO courses VALUES (null, 'BSED', 'BACHELOR OF SECONDARY EDUCATION', 1, 1,NULL,NULL);
INSERT INTO courses VALUES (null, 'BEED', 'BACHELOR OF ELEMENTARY EDUCATION', 1, 1,NULL,NULL);
INSERT INTO courses VALUES (null, 'BSHRM', 'BACHELOR OF SCIENCE IN HOTEL AND RESTAURANT MANAGEMENT', 1, 1,NULL,NULL);
INSERT INTO courses VALUES (null, 'BSCRIM', 'BACHELOR OF SCIENCE IN CRIMINOLOGY', 1, 1,NULL,NULL);
INSERT INTO courses VALUES (null, 'BSMID', 'BACHELOR OF SCIENCE IN MIDWIFERY', 1, 1,NULL,NULL);
INSERT INTO courses VALUES (null, 'BSBA', 'BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION', 1, 1,NULL,NULL);
INSERT INTO courses VALUES (null, 'BSA', 'BACHELOR OF SCIENCE IN ACCOUNTANCY', 1, 1,NULL,NULL);
INSERT INTO courses VALUES (null, 'BSACT', 'BACHELOR OF SCIENCE IN ACCOUNTING TECHNOLOGY', 1, 1,NULL,NULL);

