INSERT INTO majors VALUES (null, 'ENGLISH', 1,NULL,NULL);
INSERT INTO majors VALUES (null, 'MATHEMATICS', 1,NULL,NULL);
INSERT INTO majors VALUES (null, 'FILIPINO', 1,NULL,NULL);
INSERT INTO majors VALUES (null, 'FINANCING', 1,NULL,NULL);
INSERT INTO majors VALUES (null, 'MANAGEMENT', 1,NULL,NULL);
INSERT INTO majors VALUES (null, 'SCIENCE', 1,NULL,NULL);
